# Generated by Django 6.0.8 on 2026-09-30 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('url', models.CharField(max_length=2048)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Время ответа в миллисекундах', null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат проверки',
                'verbose_name_plural': 'Результаты проверок',
                'db_table': 'check_results',
                'indexes': [models.Index(fields=['task_id'], name='check_resul_task_id_1f2493_idx')],
            },
        ),
    ]
